@Library('pipeline_templates') _

monorepoAngularAwsTemplate {
    // Nombre del proyecto al que pertenece este componente
    projectName = 'agencia-viajes'
    // path desde la raíz del repositorio para encontrar los fuentes del proyecto
    project_home_path = 'codigo/agencia-viajes-frontend/viajes-frontend'
    // path desde el project_home_path para encontrar el artefacto
    artifactPath = 'dist'
    // nombre del repositorio en artifactory donde se guardarán los artefactos
    artifactoryRepoName = 'agencia-viajes'

    // regex para encontrar el reporte de test en formato JUnit, desde el project_home_path
    jUnitTestReport = 'coverage/junit.xml'
    coverageReport = 'coverage/coverage.xml'

    // 'true' para que se ejecute el paso integration tests de IC, 'false' para que no se ejecute
    executeIntegrationTestIC = 'false'
    // regex para encontrar el reporte de integration-test en formato JUnit, desde el project_home_path
    jIntegrationTestReport = ''

    // 'true' para que se ejecute el paso aceptance tests de IC, 'false' para que no se ejecute
    executeAceptanceTestIC = 'false'
    // regex para encontrar el reporte de aceptance-test en formato JUnit, desde el project_home_path
    jAceptanceTestReport = ''

    // AWS S3 images copy
    executeImagesToS3 = 'false'
    // CDN profile
    awsCdnProfile = 'TODO'
    // List of statics folders, and AWS repos
    awsStaticList=[]



    //AWS
    awsRegion = 'us-west-2'
    awsEcrImageName = 'agencia-viajes/viajes-front-prueba'
    awsImageTag = '1.0'
    awsEcsFamilyTaskDefinition = 'viajes-front-prueba'
    awsEcsServiceName = 'viajes-front-prueba'

    // AWS Dllo
    awsIamProfileDllo = 'TODO'
    awsEcsUrlDllo = 'TODO'
    awsEcsClusterDllo = 'cluster-agencia-viajes-desa'
    smokeTestUrlDllo = 'TODO'

    // 'true' para que se ejecute el paso E2E tests (SerenityBDD) en Dllo, 'false' para que no se ejecute
    executeE2eTestDllo = 'true'
    // URL del repositorio de SerenityBDD para el proyecto
    gitE2eUrl = ''
    // regex para encontrar el reporte de e2e test en formato JUnit, desde el home del proyecto SerenityBDD
    je2eTestReport = 'target/site/serenity/*.xml'
    // path donde se encuentra el index.html generado por SerenityBDD, desde el home del proyecto SerenityBDD
    htmle2eTestReport = 'target/site/serenity'

    // AWS QA
    awsIamProfileQa = 'TODO'
    awsEcsUrlQa = 'TODO'
    awsEcsClusterQa = 'cluster-agencia-viajes-test'
    smokeTestUrlQa = 'TODO'

    // 'true' para que se ejecute el paso integration tests (postman) en QA, 'false' para que no se ejecute
    executeIntegrationTestQa = 'false'

    // 'true' para que se ejecute el paso E2E tests (SerenityBDD) en Dllo, 'false' para que no se ejecute
    executeE2eTestQa = 'false'
    
    supportEmail = 'luis.polo@sura.pe'
}